project_id = "zspcdvtdgssabpqrybib"

[functions.update-user-name]
verify_jwt = true

[functions.generate-follow-ups]
verify_jwt = false

[functions.cleanup-duplicates]
verify_jwt = false

[functions.rotina-whatsapp-response]
verify_jwt = false

[functions.notify-resumo-semanal-pergunta]
verify_jwt = false

[functions.resumo-semanal-webhook-resposta]
verify_jwt = false

[functions.notify-formulario-encerramento]
verify_jwt = false


[functions.agente-atendimento-webhook]
verify_jwt = false
