// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-unidades.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-unidades.ts
var list_unidades_default = defineTool({
  name: "list_unidades",
  title: "Listar unidades",
  description: "Lista as unidades (academias) que o usu\xE1rio autenticado pode acessar, com id e nome. Use o id retornado para filtrar leads e contas.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("unidades").select("id, nome, slug, ativo").order("nome");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { unidades: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_leads_default = defineTool2({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista leads do CRM da unidade informada (ou de todas as unidades permitidas), com filtros por status do funil, busca por nome/telefone e per\xEDodo de cadastro.",
  inputSchema: {
    unidade_id: z.string().uuid().optional().describe("Filtra por unidade. Use list_unidades para obter o id."),
    status_funil: z.string().optional().describe("Status do funil, ex.: novo, em_negociacao, aula_agendada, matriculado, perdido."),
    search: z.string().trim().min(2).optional().describe("Busca por nome, e-mail ou telefone."),
    dias: z.number().int().min(1).max(365).optional().describe("Somente leads cadastrados nos \xFAltimos N dias."),
    apenas_ativos: z.boolean().optional().describe("Se true (padr\xE3o), ignora leads inativos."),
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unidade_id, status_funil, search, dias, apenas_ativos, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select(
      "id, nome, telefone, email, origem, status_funil, unidade_id, plano_escolhido, data_aula_experimental, hora_aula_experimental, is_matriculado, ativo, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (unidade_id) query = query.eq("unidade_id", unidade_id);
    if (status_funil) query = query.eq("status_funil", status_funil);
    if (apenas_ativos !== false) query = query.eq("ativo", true);
    if (dias) {
      const desde = new Date(Date.now() - dias * 24 * 60 * 60 * 1e3).toISOString();
      query = query.gte("created_at", desde);
    }
    if (search) {
      const digits = search.replace(/\D/g, "");
      const termo = `%${search}%`;
      const filtros = [`nome.ilike.${termo}`, `email.ilike.${termo}`, `telefone.ilike.${termo}`];
      if (digits.length >= 4) filtros.push(`telefone_normalizado.ilike.%${digits}%`);
      query = query.or(filtros.join(","));
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: data?.length ?? 0, leads: data ?? [] }) }],
      structuredContent: { total: data?.length ?? 0, leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_lead_default = defineTool3({
  name: "get_lead",
  title: "Detalhes do lead",
  description: "Retorna os dados completos de um lead (por id ou telefone) junto com o hist\xF3rico de intera\xE7\xF5es e agendamentos.",
  inputSchema: {
    lead_id: z2.string().uuid().optional().describe("Id do lead."),
    telefone: z2.string().trim().min(8).optional().describe("Telefone do lead, com ou sem m\xE1scara.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id, telefone }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    if (!lead_id && !telefone) {
      return { content: [{ type: "text", text: "Informe lead_id ou telefone." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let leadQuery = supabase.from("leads").select("*").limit(1);
    if (lead_id) {
      leadQuery = leadQuery.eq("id", lead_id);
    } else {
      const digits = (telefone ?? "").replace(/\D/g, "");
      leadQuery = leadQuery.ilike("telefone_normalizado", `%${digits}%`);
    }
    const { data: leads, error } = await leadQuery;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const lead = leads?.[0];
    if (!lead) return { content: [{ type: "text", text: "Lead n\xE3o encontrado." }], isError: true };
    const { data: interacoes, error: interError } = await supabase.from("interacoes").select("*").eq("lead_id", lead.id).order("data_interacao", { ascending: false }).limit(50);
    if (interError) return { content: [{ type: "text", text: interError.message }], isError: true };
    const payload = { lead, interacoes: interacoes ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var ORIGENS = [
  "WHATSAPP",
  "INSTAGRAM",
  "TR\xC1FEGO PAGO",
  "INDICA\xC7\xC3O",
  "VISITA PRESENCIAL",
  "TERCEIROS",
  "N\xC3O INFORMADO"
];
var create_lead_default = defineTool4({
  name: "create_lead",
  title: "Cadastrar lead",
  description: "Cadastra um novo lead no CRM em uma unidade. Bloqueia telefone duplicado dentro da mesma unidade (o mesmo telefone pode existir em unidades diferentes).",
  inputSchema: {
    nome: z3.string().trim().min(3).describe("Nome completo do lead."),
    telefone: z3.string().trim().min(8).describe("Telefone com DDD."),
    unidade_id: z3.string().uuid().describe("Unidade do cadastro. Use list_unidades."),
    origem: z3.enum(ORIGENS).optional().describe("Origem do lead (padr\xE3o N\xC3O INFORMADO)."),
    email: z3.string().email().optional(),
    observacoes: z3.string().trim().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ nome, telefone, unidade_id, origem, email, observacoes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const digits = telefone.replace(/\D/g, "");
    const { data: existentes, error: dupError } = await supabase.from("leads").select("id, nome, ativo").eq("unidade_id", unidade_id).ilike("telefone_normalizado", `%${digits}%`).limit(1);
    if (dupError) return { content: [{ type: "text", text: dupError.message }], isError: true };
    if (existentes?.length) {
      return {
        content: [
          {
            type: "text",
            text: `Telefone j\xE1 cadastrado nesta unidade para "${existentes[0].nome}" (id ${existentes[0].id}).`
          }
        ],
        isError: true
      };
    }
    const nomeUpper = nome.toUpperCase();
    const { data, error } = await supabase.from("leads").insert({
      nome: nomeUpper,
      telefone,
      email: email ?? null,
      unidade_id,
      origem: origem ?? "N\xC3O INFORMADO",
      observacoes: observacoes ? observacoes.toUpperCase() : null,
      status_funil: "novo",
      ativo: true,
      created_by: ctx.getUserId(),
      cadastrado_por: ctx.getUserEmail() ?? null
    }).select("id, nome, telefone, unidade_id, status_funil, created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { lead: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/list-contas-pagar.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_contas_pagar_default = defineTool5({
  name: "list_contas_pagar",
  title: "Listar contas a pagar",
  description: "Lista as contas a pagar de uma unidade, com filtro por status (pendente, pago, cancelado) e por intervalo de vencimento.",
  inputSchema: {
    unidade_id: z4.string().uuid().optional().describe("Filtra por unidade. Use list_unidades."),
    status: z4.string().optional().describe("Status da conta, ex.: pendente, pago, cancelado."),
    vencimento_de: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Vencimento inicial (YYYY-MM-DD)."),
    vencimento_ate: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Vencimento final (YYYY-MM-DD)."),
    limit: z4.number().int().min(1).max(200).optional().describe("M\xE1ximo de registros (padr\xE3o 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unidade_id, status, vencimento_de, vencimento_ate, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contas_pagar").select(
      "id, descricao, valor, data_vencimento, status, unidade_id, fornecedor, categoria, valor_pago, data_pagamento"
    ).is("deleted_at", null).order("data_vencimento", { ascending: true }).limit(limit ?? 50);
    if (unidade_id) query = query.eq("unidade_id", unidade_id);
    if (status) query = query.eq("status", status);
    if (vencimento_de) query = query.gte("data_vencimento", vencimento_de);
    if (vencimento_ate) query = query.lte("data_vencimento", vencimento_ate);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((acc, c) => acc + Number(c.valor ?? 0), 0);
    const payload = { quantidade: data?.length ?? 0, valor_total: total, contas: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zspcdvtdgssabpqrybib";
var mcp_default = defineMcp({
  name: "evo-club-crm",
  title: "EVO CLUB CRM",
  version: "0.1.0",
  instructions: "Ferramentas do EVO CLUB CRM (academias EVO). Comece por `list_unidades` para descobrir as unidades do usu\xE1rio; use `list_leads` e `get_lead` para consultar o CRM, `create_lead` para cadastrar um novo lead e `list_contas_pagar` para o financeiro. Todos os dados s\xE3o restritos \xE0s unidades do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_unidades_default, list_leads_default, get_lead_default, create_lead_default, list_contas_pagar_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
